---

- name: Add user to docker group
  user:
    name: icon
    groups: docker
    append: yes

- name: Install pip3 packages
  pip:
    name: "{{ pippkgs }}"
    executable: pip3
    state: present
  vars:
    pippkgs:
      - pip
      - docker
      - docker-compose
      - PyYAML

- name: Create data directory
  file:
    path: /home/icon/data
    mode: '0755'
    state: directory
    owner: icon
    group: icon

- name: Create cert directory
  file:
    path: /home/icon/cert
    mode: '0600'
    state: directory
    owner: icon
    group: icon

- name: Copy over the keystore
  copy:
    src: "{{ keystore_path }}"
    dest: /home/icon/cert/{{ keystore_path | basename }}
    mode: '0600'
    owner: icon
    group: icon

- name: Render the docker-compose file
  template:
    src: "{{ role_path }}/templates/docker-compose.yml.j2"
    dest: /home/icon/docker-compose.yml
    mode: '0644'
    owner: icon
    group: icon
  tags: update-configs

- name: Copy service
  template:
    src: "{{ role_path }}/templates/prep.service.j2"
    dest: /etc/systemd/system/prep.service
    owner: root
    group: root
    mode: 0600
